source: .
permalink: /blog/:year/:month/:day/:title
include: [".well-known/"]
highlighter: rouge
exclude:
  - vendor/
repository: https://github.com/tkellogg/tkellogg.github.com

# Bluesky threads collection
collections:
  threads:
    output: true
    permalink: /threads/:name/

# All this needed to insert $$latex$$ in markdown
markdown: kramdown
kramdown:
  math_engine: katex

